---
 - name: Installing HTTPD
   hosts: web
   become: true
   gather_facts: false
   vars:
     pkg: httpd
   tasks:
     - shell: rpm -q httpd | head -n 1  //check pkg is installed or not
       args:
         warn: false
       register: result  //output is stored in result
       changed_when: false
     - fail:
         msg: "Failed because {{ pkg }} is already installed"
       when: "'not installed' not in result.stdout"
     - debug:
        msg: do we get here
     - yum:
        name: "{{ pkg }}"
        state: present
   ...


        NOTE:playbook should install package only when package is not installed. this is for centos and rhel distribution. rpm should replaced with apt
        Follow httpd installation in Ansible playbooks zipped file
